# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Automock < Formula
  desc "AutoMock CLI – generate & deploy MockServer infra"
  homepage "https://github.com/hemantobora/auto-mock"
  version "2.0.2"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/hemantobora/auto-mock/releases/download/v2.0.2/automock_2.0.2_darwin_amd64.tar.gz"
      sha256 "23a4d86aedea6920fe23030b13eca929f1895313efa916451d5addec781d3cb6"

      def install
        bin.install "automock"
      end
    end
    on_arm do
      url "https://github.com/hemantobora/auto-mock/releases/download/v2.0.2/automock_2.0.2_darwin_arm64.tar.gz"
      sha256 "60480265a0eb61926888ba4d35f6c78ad6d84c796ff13f87050fbd6a95c5a46d"

      def install
        bin.install "automock"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/hemantobora/auto-mock/releases/download/v2.0.2/automock_2.0.2_linux_amd64.tar.gz"
        sha256 "ed602260130d119961b8961ca858e52c8dc8ab3232a2ecdafa63afe420f6f3c6"

        def install
          bin.install "automock"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/hemantobora/auto-mock/releases/download/v2.0.2/automock_2.0.2_linux_arm64.tar.gz"
        sha256 "5d2e48c5d8aa8576c4a7dbcb3b0e314f4df9762b22cfdba66aa6ced485c9a0c6"

        def install
          bin.install "automock"
        end
      end
    end
  end

  test do
    system "#{bin}/automock", "--version"
  end
end
