# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Automock < Formula
  desc "AutoMock CLI – generate & deploy MockServer infra"
  homepage "https://github.com/hemantobora/auto-mock"
  version "2.0.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/hemantobora/auto-mock/releases/download/v2.0.1/automock_2.0.1_darwin_amd64.tar.gz"
      sha256 "4ce3d1ae44d456d391567f199ff520ffb0e290f2ef9145101515603b1cd94504"

      def install
        bin.install "automock"
      end
    end
    on_arm do
      url "https://github.com/hemantobora/auto-mock/releases/download/v2.0.1/automock_2.0.1_darwin_arm64.tar.gz"
      sha256 "81603726dd2ed0c88bc91432ae6fd3f66f893d3909eb8e5e7c9864eae5a7aaf8"

      def install
        bin.install "automock"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/hemantobora/auto-mock/releases/download/v2.0.1/automock_2.0.1_linux_amd64.tar.gz"
        sha256 "379ceacfc60571b75126a2424414dcb7ebce0faa5590b2eb0389abe4ea154795"

        def install
          bin.install "automock"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/hemantobora/auto-mock/releases/download/v2.0.1/automock_2.0.1_linux_arm64.tar.gz"
        sha256 "9d90461a00e83d5c4d3a44591044908ff71228f4c6284ac5aa65bf229a428054"

        def install
          bin.install "automock"
        end
      end
    end
  end

  test do
    system "#{bin}/automock", "--version"
  end
end
