# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Automock < Formula
  desc "AutoMock CLI – generate & deploy MockServer infra"
  homepage "https://github.com/hemantobora/auto-mock"
  version "1.0.6"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/hemantobora/auto-mock/releases/download/v1.0.6/automock_1.0.6_darwin_amd64.tar.gz"
      sha256 "88027e8559d3738ccdb30c163b2a808db9836b31771ff470f52df9bdebb5ab5d"

      def install
        bin.install "automock"
      end
    end
    on_arm do
      url "https://github.com/hemantobora/auto-mock/releases/download/v1.0.6/automock_1.0.6_darwin_arm64.tar.gz"
      sha256 "9101d20304ea15028ad257605fa30624bd426ee23eb40ac9513c22a97918ba03"

      def install
        bin.install "automock"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/hemantobora/auto-mock/releases/download/v1.0.6/automock_1.0.6_linux_amd64.tar.gz"
        sha256 "c3175139360e84e307852ed471c410264c717b77c993800a1c3d0b0d1b396de9"

        def install
          bin.install "automock"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/hemantobora/auto-mock/releases/download/v1.0.6/automock_1.0.6_linux_arm64.tar.gz"
        sha256 "296972ff3b91d705ee6ee72e728f4c828fdd876b1ababef49d03574b3e5d72ed"

        def install
          bin.install "automock"
        end
      end
    end
  end

  test do
    system "#{bin}/automock", "--version"
  end
end
